### ISSUE TITLE
android - ошибка чтения wallet.dat

### ISSUE THREAD

**Issue by hypnosis-i2p** [GOSTSec/gostcoin#25]
Каждый раз при запуске:

![image](https://user-images.githubusercontent.com/19966907/33517782-396894b6-d7c5-11e7-96e9-e1a326bcdf80.png)

Это госткойн андройд

от скомороха

**Comment by r4sas** [comment]
https://github.com/GOSTSec/gostcoin/commit/01e853f233a605fdc490be4c7fb8b4014238f278
Нужно проверить текущий транк.

**Comment by r4sas** [comment]
Исправлено в https://github.com/GOSTSec/gostcoin/commit/01e853f233a605fdc490be4c7fb8b4014238f278
