### ISSUE TITLE
Cannot build gostcoind

### ISSUE THREAD

**Issue by MegaLite** [GOSTSec/gostcoin#28]
Failed target obj/bitcoinrpc.o with /usr/local/include/boost/asio/ssl/detail/impl/engine.ipp:221:9: note: suggested alternative: ‘SSL_F_SSL_READ’

**Comment by MegaLite** [comment]
1.62

**Comment by r4sas** [comment]
Please send full log via paste service (https://paste.i2pd.xyz for example)

**Comment by MegaLite** [comment]
Ok, https://paste.i2pd.xyz/?7454e2d36713fe7f#BPovWmPMyEXQ4/kTqKcsQdZjwzIjjdZbA0ZHXuqmA98=

**Comment by MegaLite** [comment]
dpkg -l|grep libssl
ii  libssl-dev:amd64                       1.1.0h-2                                amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                             1.1.0h-2                                all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                      1.0.1t-1+deb8u8                         amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.0.2:amd64                      1.0.2o-1                                amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                        1.1.0h-2                                amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:i386                         1.1.0h-2                                i386         Secure Sockets Layer toolkit - shared libraries

**Comment by orignal** [comment]
are you trying to build trunk ?

**Comment by MegaLite** [comment]
Maybe no.. I clone https://github.com/GOSTSec/gostcoin.git then cd to folder, when make -f makefile.unix

**Comment by orignal** [comment]
That's definitely openssl 1.1 issue, but it should be fixed in trunk

**Comment by MegaLite** [comment]
I need clone openssl 1.1 trunk and compile, right?

**Comment by orignal** [comment]
Try to build with openssl 1.0.2

**Comment by MegaLite** [comment]
Plz tell me how it better made in this case.. In builds i beginner:)

**Comment by orignal** [comment]
Тебе же ясно сказали: собирать  с openssl 1.0.2. За тебя никто это делать не станет

**Comment by MegaLite** [comment]
Них не ясно)) (ништяк, что по русски) куда дешевле будет  воткнуть путь к заголовочным файлам SSL этой версии?

**Comment by orignal** [comment]
boost 1.62 насколько я знаю с openssl 1.1 вообще не собирается

**Comment by MegaLite** [comment]
Кажется, дело решилось при помощи принудительного отката libssl-dev на backports-версию 1.0.2. Также знающие подсказали, что можно было -I вкорячить в Makefile, если бы исходники валялись где-то "там".
