### ISSUE TITLE
gostcoin-qt windows настройки в реестре вместо конфига?

### ISSUE THREAD

**Issue by khoss** [GOSTSec/gostcoin#40]
А вот обязательно настройки в реестре хранить? 
Почему бы не вынести все в конфиг-файла?
Например HKEY_CURRENT_USER\SOFTWARE\GOSTSec\GOSTcoin-Qt\I2P
параметр samhost в клиенте поменял промахнувшись, перезапустил и все, пока в реестре не найдешь ничего не сделаешь. Даже если грохнешь все в %appdata% - ничего не взлетит.

**Comment by r4sas** [comment]
Это изначально так сделано в Qt, так что о этом ни кто не заботился, особенно на винде.
Если вы найдете как эту фигню прибить, то буду очень благодарен, ибо времени не хватает заниматься поисками.

**Comment by r4sas** [comment]
Копать надо в сторону QSettings, если что.

**Comment by khoss** [comment]
Я не погромист совсем =( Но попробую. А в самом кошельке-клиенте-qt можно как то сделать приоритет что бы в конфиге данные были первичными? Просто для обычного человека это фатально - в гуях поменял настройки и все-клиент накрылся

**Comment by khoss** [comment]
Вот нашел что вроде как можно задать тип хранения https://doc.qt.io/archives/qt-4.8/qsettings.html#Format-enum

**Comment by khoss** [comment]
Провел эксперимент.. Оказывается клиент приоритетно и так читает все из gostcoin.conf
Нужно лишь принудительно писать опции туда а не по дефолту куда QT пишет.. 
или достаточно запустить gostcoin-qt с параметром --help что бы увидеть все опции  и дальше уже можно сориентироваться/починить сломанный клиент
В моем случае помогла запись в _%appdata%/gostcoin/gostcoin.conf_ строчка **samhost=127.0.0.1**
